# Generated by Django 3.2.18 on 2023-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etag', models.CharField(default='', max_length=255)),
                ('table_info_type', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
